In [138]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])



array([0, 0, 2])

##**【問題1】行列積を手計算する**

\begin{eqnarray}
A=\left[
\begin{array}{ccc}
-1 & 2 & 3 \\
4 & -5 & 6 \\
7 & 8 & -9 \\
\end{array}
\right]
,B=\left[
\begin{array}{ccc}
0 & 2 & 1 \\
0 & 2 & -8 \\
2 & 9 & -1 \\
\end{array}
\right]
\end{eqnarray}<br>
AとBの行列積を手計算で解いてください。


計算過程もマークダウンテキストを用いて説明してください。


___
以下のような計算をする

$$
\begin{bmatrix}
(-1*0)+(2*0)+(3*2) & (-1*2)+(2*2)+(3*9) & (-1*1)+(2*-8)+(3*-1)\\
(4*0)+(-5*0)+(6*2) & (4*2)+(-5*2)+(6*9) & (4*1)+(-5*-8)+(6*-1)\\
(7*0)+(8*0)+(-9*2) & (7*2)+(8*2)+(-9*9) & (7*1)+(8*-8)+(-9*-1)\\
\end{bmatrix}
$$

$$
\begin{bmatrix}
6 &29&-20\\
12& 52& 38\\
-18& 51& 48\\
\end{bmatrix}
$$

##**【問題2】NumPyの関数による計算**
この行列積はNumPyのnp.matmul()やnp.dot()、または@演算子を使うことで簡単に計算できます。


これらを使い行列積を計算してください。



In [2]:
cal_dot = np.dot(a_ndarray, b_ndarray)
cal_dot

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

In [3]:
cal_matmul = np.matmul(a_ndarray, b_ndarray)
cal_matmul

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

In [4]:
cal_at = a_ndarray @ b_ndarray
cal_at

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

##**【問題3】ある要素の計算を実装**
$$
\sum^{2}_{k=0}a_{0,k}b_{k,0}
$$


In [18]:
a = a_ndarray
b = b_ndarray

cal_one = a[0,0]*b[0,0]+a[0,1]*b[1,0]+a[0,2]*b[2,0]
cal_one

6

In [22]:
a = a_ndarray
b = b_ndarray

cal_one = a[0][0]*b[0][0]+a[0][1]*b[1][0]+a[0][2]*b[2][0]
cal_one

6

In [117]:
for k in range(len(a_ndarray)):
  ans_ab = a_ndarray[0][k]*b_ndarray[k][0]
ans_ab

6

##**【問題4】行列積を行う関数の作成**
問題3のコードを拡張し、行列積のスクラッチ実装を完成させてください。行列AとBを引数に受け取り、行列積を返す関数としてください。



In [162]:
def matrix_loading_generator(matrix_a, matrix_b):
  matrix_loading = np.zeros((matrix_a.shape[0],matrix_b.shape[0]))
  for i in range(matrix_a.shape[0]):
    for j in range(matrix_b.shape[1]):
      for k in range(matrix_a.shape[1]):
        matrix_loading[i, j] += matrix_a[i, k] * matrix_b[k, j]
  return matrix_loading

matrix_loading_generator(a_ndarray, b_ndarray)

array([[  6.,  29., -20.],
       [ 12.,  52.,  38.],
       [-18., -51., -48.]])

##**【問題5】計算が定義されない入力を判定する**

問4で作成した関数に入力された形が同じかどうか判断する式を入れる

In [163]:
def matrix_loading_generator_kai(matrix_a, matrix_b):
  a_array_type = matrix_a[0].shape 
  b_column = matrix_b[0:,0]
  b_column_type = b_column.shape
  if a_array_type != b_column_type:
    print("入力した行列の列数と行数が等しくなく計算できません。入力したデータの形を確認してください") 
  else:
    matrix_loading = np.zeros((matrix_a.shape[0],matrix_b.shape[0]))
    for i in range(matrix_a.shape[0]):
      for j in range(matrix_b.shape[1]):
        for k in range(matrix_a.shape[1]):
          matrix_loading[i, j] += matrix_a[i, k] * matrix_b[k, j]
    return matrix_loading

matrix_loading_generator_kai(a_ndarray, b_ndarray)

array([[  6.,  29., -20.],
       [ 12.,  52.,  38.],
       [-18., -51., -48.]])

___
入力される方に問題がある例をテスト

In [164]:
d_ndarray_ = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

matrix_loading_generator_kai(d_ndarray_, e_ndarray)

入力した行列の列数と行数が等しくなく計算できません。入力したデータの形を確認してください


##**【問題6】転置**

___
np.transpose()

In [166]:
e_ndarray_tr = np.transpose(e_ndarray)
e_ndarray_tr

array([[-9,  6],
       [ 8, -5],
       [ 7,  4]])

In [167]:
matrix_loading_generator_kai(d_ndarray_, e_ndarray_tr)

array([[ 46.,  -4.,   0.],
       [-34.,  73.,   0.]])

___
.T

In [168]:
e_ndarray_T = e_ndarray.T
e_ndarray_T

array([[-9,  6],
       [ 8, -5],
       [ 7,  4]])

In [169]:
matrix_loading_generator_kai(d_ndarray_, e_ndarray_T)

array([[ 46.,  -4.,   0.],
       [-34.,  73.,   0.]])