In [23]:
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import load_iris
data = load_iris()
X = data.data[:10]
scaler = StandardScaler()
scaler.fit(X)
scaler.mean_
scaler.var_
X_std = scaler.transform(X)
X_std

array([[ 0.86828953,  0.65207831, -0.48795004, -0.26726124],
       [ 0.14471492, -1.06391725, -0.48795004, -0.26726124],
       [-0.57885968, -0.37751902, -1.46385011, -0.26726124],
       [-0.94064699, -0.72071813,  0.48795004, -0.26726124],
       [ 0.50650222,  0.99527742, -0.48795004, -0.26726124],
       [ 1.95365143,  2.02487476,  2.43975018,  2.40535118],
       [-0.94064699,  0.3088792 , -0.48795004,  1.06904497],
       [ 0.50650222,  0.3088792 ,  0.48795004, -0.26726124],
       [-1.66422159, -1.40711636, -0.48795004, -0.26726124],
       [ 0.14471492, -0.72071813,  0.48795004, -1.60356745]])

##**問題1　これまで利用してきたクラスの列挙**

**Pandas**
___
* DataFrame
* Series<br>
<br>

**matplotlib**
___
* Pyplot
* Figure
* Axes<br>
<br>

**scikit-learn**
___
* SVC
* DecisionTreeRegressor

##**問題2　これまで利用してきたメソッドやインスタンス変数**


___
append<br>
join<br>
items<br>
sort<br>
iloc<br>
loc<br>



##**問題3　標準化クラスをスクラッチで作成**

In [27]:
class ScratchStandardScaler():
    """
    標準化のためのクラス
    Attributes
    ----------
    mean_ : 次の形のndarray, shape(n_features,)
        平均
    var_ : 次の形のndarray, shape(n_features,)
        分散
    """
    def fit(self, X):
        """
        標準化のために平均と標準偏差を計算する。
        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            訓練データ
        """
        self.mean_ = X.mean()
        self.var_ = X.var()
        pass
    def transform(self, X):
        """
        fitで求めた値を使い標準化を行う。
        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            特徴量
        Returns
        ----------
        X_scaled : 次の形のndarray, shape (n_samples, n_features)
            標準化された特緒量
        """
        X -= self.mean_
        X_scaled = X
        pass
        return X_scaled



In [28]:
import numpy as np
from sklearn.datasets import load_iris
data = load_iris()
X = data.data[:10]
scratch_scaler = ScratchStandardScaler()
scratch_scaler.fit(X)
print("平均 : {}".format(scratch_scaler.mean_))
print("分散 : {}".format(scratch_scaler.var_))
X_std = scratch_scaler.transform(X)
print(X_std)

平均 : 2.46
分散 : 3.1744
[[ 2.64  1.04 -1.06 -2.26]
 [ 2.44  0.54 -1.06 -2.26]
 [ 2.24  0.74 -1.16 -2.26]
 [ 2.14  0.64 -0.96 -2.26]
 [ 2.54  1.14 -1.06 -2.26]
 [ 2.94  1.44 -0.76 -2.06]
 [ 2.14  0.94 -1.06 -2.16]
 [ 2.54  0.94 -0.96 -2.26]
 [ 1.94  0.44 -1.06 -2.26]
 [ 2.44  0.64 -0.96 -2.36]]


##**問題4　四則演算を行うクラスを作成**

In [93]:
class ExampleClass():
    """
    説明用の簡単なクラス
    Parameters
    ----------
    value : float or int
        初期値
    Attributes
    ----------
    value : float or int
        計算結果
    """
    def __init__(self, value):
        self.value = value
        if str(value).isdigit():
            print("初期値{}が設定されました".format(self.value))
        else:
            print("エラー")
    def add(self, value2):
        """
        受け取った引数をself.valueに加える
        """
        self.value += value2
    def diff(self, value2):
        """
        受け取った引数をself.valueから引く
        """
        self.value -= value2
    def multi(self, value2):
        """
        受け取った引数をself.valueにかける
        """
        self.value *= value2    
    def division(self, value2):
        """
        受け取った引数をself.valueから割る
        """
        self.value /= value2


In [49]:
example = ExampleClass(5)
print("value(初期値) : {}".format(example.value))
example.add(3)
print("value(足し算) : {}".format(example.value))
example.diff(3)
print("value(引き算) : {}".format(example.value))
example.multi(3)
print("value(掛け算) : {}".format(example.value))
example.division(3)
print("value(割り算) : {}".format(example.value))

初期値5が設定されました
value(初期値) : 5
value(足し算) : 8
value(引き算) : 5
value(掛け算) : 15
value(割り算) : 5.0


In [129]:
example2 = ExampleClass(5)
example2.division(5)
print("value(割り算) : {}".format(example2.value))


初期値5が設定されました
value(割り算) : 1.0


In [132]:
test = "A"
ExampleClassPlus(test)


エラー
